---
# Source: epinio-application-stateful/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    epinio.io/created-by: user
  labels:
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/part-of: default
    helm.sh/chart: epinio-application-stateful-0.1.23
    app.kubernetes.io/name: placeholder
    app.kubernetes.io/component: application
  name: r-ff55435345834a3fe224936776c2aa15f6ed5358
  namespace:  default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: placeholder
    app.kubernetes.io/component: application
  type: ClusterIP
---
# Source: epinio-application-stateful/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    epinio.io/created-by: user
  labels:
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/part-of: default
    helm.sh/chart: epinio-application-stateful-0.1.23
    app.kubernetes.io/name: placeholder
    app.kubernetes.io/component: application
  name: r-67369845caa8bf95b62878274feb7b00146f0daf
  namespace:  default
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: placeholder
    app.kubernetes.io/component: application
---
# Source: epinio-application-stateful/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: r-ff55435345834a3fe224936776c2aa15f6ed5358
  namespace: default
  labels:
    app.kubernetes.io/managed-by: epinio
    app.kubernetes.io/part-of: default
    helm.sh/chart: epinio-application-stateful-0.1.23
    app.kubernetes.io/name: placeholder
    app.kubernetes.io/component: application
  annotations:
    epinio.io/created-by: user
spec:
  serviceName: r-67369845caa8bf95b62878274feb7b00146f0daf
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: placeholder
  template:
    metadata:
      annotations:
        app.kubernetes.io/name: placeholder
        epinio.io/created-by: user
      labels:
        app.kubernetes.io/managed-by: epinio
        app.kubernetes.io/part-of: default
        helm.sh/chart: epinio-application-stateful-0.1.23
        app.kubernetes.io/name: placeholder
        app.kubernetes.io/component: application
        epinio.io/stage-id: "999"
        epinio.io/app-container: r-ff55435345834a3fe224936776c2aa15f6ed5358
    spec:
      serviceAccount: default
      serviceAccountName: default
      automountServiceAccountToken: true
      containers:
      - name: r-ff55435345834a3fe224936776c2aa15f6ed5358
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        image: 
        imagePullPolicy: IfNotPresent
  volumeClaimTemplates:
  - metadata:
      name: stateful
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
