---
# Source: evi-kes/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: minio
  name: kes-config
data:

  kes-config.yaml: "# INTEL CONFIDENTIAL\n#\n# Copyright (C) 2022 Intel Corporation.\n#\n#
    This software and the related documents are Intel copyrighted materials, and your
    use of\n# them is governed by the express license under which they were provided
    to you (License).\n# Unless the License provides otherwise, you may not use, modify,
    copy, publish, distribute,\n# disclose or transmit this software or the related
    documents without Intel's prior written permission.\n#\n# This software and the
    related documents are provided as is, with no express or implied warranties,\n#
    other than those that are expressly stated in the License.\n\n---\naddress: 0.0.0.0:7373\n\nadmin:\n
    \ identity: \"disabled\"\n\ntls:\n  key: /pki/kes-server.key\n  cert: /pki/kes-server.crt\n\npolicy:\n
    \ minio:\n    allow:\n    - /v1/key/create/minio-*\n    - /v1/key/generate/minio-*\n
    \   - /v1/key/decrypt/minio-*\n    - /v1/key/list/minio-*\n    identities:\n    -
    ${APP_IDENTITY}\n\ncache:\n  expiry:\n    any:    5m0s \n    unused: 20s\n\nlog:\n
    \ error: on\n  audit: on\n\nkeystore:\n  vault:\n    endpoint: https://vault.dev:8200\n
    \   prefix: minio\n    approle:\n      id: ${APP_ROLE_ID} # Your AppRole ID\n      secret:
    ${APP_SECRET_ID} # Your AppRole Secret ID\n      retry:  15s\n    status:\n      ping:
    10s\n    tls:\n      ca: \"/pki/vault-server.crt\" # Since we use self-signed certificates\n"
---
# Source: evi-kes/templates/kes-svc-nodeport.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: evi-kes-svc-node
spec:
  type: NodePort
  selector:
    app: evi-kes
  ports:
  - protocol: TCP
    port: 7373
    targetPort: 7373
    nodePort: 30737
---
# Source: evi-kes/templates/kes-svc.yaml
apiVersion: v1
kind: Service
metadata:
  namespace: minio
  name: evi-kes-svc
spec:
  selector:
    app: evi-kes
  ports:
  - protocol: TCP
    port: 7373
    targetPort: 7373
---
# Source: evi-kes/templates/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minio
  name: evi-kes
  labels:
    app: evi-kes
  annotations:
    container.apparmor.security.beta.kubernetes.io/kes: runtime/default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evi-kes
  template:
    metadata:
      labels:
        app: evi-kes
    spec:
      nodeSelector:
        feature.node.kubernetes.io/cpu-cpuid.AVX512VNNI: 'true'
        feature.node.kubernetes.io/cpu-cpuid.AVX2: 'true'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: evi-kes
          image: minio/kes:2023-04-03T16-41-28Z
          workingDir: /
          command: ["/kes"]
          args: ["server", "--config=kes-config.yaml", "--auth=off"]
          imagePullPolicy: IfNotPresent
          env:
          - name: APP_IDENTITY
            valueFrom:
              secretKeyRef:
                name: vault-tls
                key: APP_IDENTITY
            value: 
          - name: APP_ROLE_ID
            valueFrom:
              secretKeyRef:
                name: vault-tls
                key: APP_ROLE_ID
          - name: APP_SECRET_ID
            valueFrom:
              secretKeyRef:
                name: vault-tls
                key: APP_SECRET_ID
          - name: VAULT_SKIP_VERIFY
            valueFrom:
              secretKeyRef:
                name: vault-env-crts
                key: VAULT_SKIP_VERIFY
          - name: KES_CLIENT_CERT
            valueFrom:
              secretKeyRef:
                name: vault-env-crts
                key: KES_CLIENT_CERT
          - name: KES_CLIENT_KEY
            valueFrom:
              secretKeyRef:
                name: vault-env-crts
                key: KES_CLIENT_KEY
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault-key
                key: VAULT_TOKEN
          ports:
          - containerPort: 7373
          volumeMounts:
          - name: kes-crts
            mountPath: "/pki"
          - mountPath: /kes-config.yaml
            subPath: kes-config.yaml
            name: kes-config
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
          resources:
            limits:
              cpu: "1"
              memory: "128Mi"
            requests:
              cpu: "10m"
              memory: "50Mi"
      volumes:
      - name: kes-crts
        secret:
          secretName: kes-crts
      - name: kes-config
        configMap:
          name: kes-config
---
# Source: evi-kes/templates/configmap.yaml
# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.
---
# Source: evi-kes/templates/deployment.yaml
# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.
---
# Source: evi-kes/templates/kes-svc-nodeport.yaml
# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.
---
# Source: evi-kes/templates/kes-svc.yaml
# INTEL CONFIDENTIAL
#
# Copyright (C) 2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you (License).
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.
