---
# Source: k8s-applier/templates/000-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-applier
  namespace: default
  labels:
    app: k8s-applier
---
# Source: k8s-applier/templates/001-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-applier
  namespace: default
  labels:
    app: k8s-applier
rules:
  - apiGroups:
    - ""
    - apps
    - extensions
    - cert-manager.io
    - networking.k8s.io
    - rbac.authorization.k8s.io
    - monitoring.coreos.com
    - policy
    - batch
    resources:
    - '*'
    verbs:
    - '*'
---
# Source: k8s-applier/templates/002-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-applier
  namespace: default
  labels:
    app: k8s-applier
roleRef:
  kind: Role
  name: k8s-applier
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: k8s-applier
    namespace: default
---
# Source: k8s-applier/templates/009-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-applier
  namespace: default
  labels:
    app: k8s-applier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-applier
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: k8s-applier
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - applier
            topologyKey: kubernetes.io/hostname 
      containers:
      - name: k8s-applier
        image: shlomibendavid/k8s-applier:0311240529
        imagePullPolicy: IfNotPresent
        args:
        - --verbose
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - mountPath: /etc/manifests
          name: manifests-volume
      restartPolicy: Always
      serviceAccountName: k8s-applier
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          name: golden-manifests
        name: manifests-volume
